// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAV-vwAWA85Llfp0l_IEaNGA4dZpjz9x0',
    appId: '1:587521772116:web:12cefff84d3b6036877bc1',
    messagingSenderId: '587521772116',
    projectId: 'medicalapp-b6c2e',
    authDomain: 'medicalapp-b6c2e.firebaseapp.com',
    databaseURL: 'https://medicalapp-b6c2e-default-rtdb.firebaseio.com',
    storageBucket: 'medicalapp-b6c2e.appspot.com',
    measurementId: 'G-ZC48PLFNML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ8u-Hdn-gfEOn1u7TGxlmZaR9Ys8VMDE',
    appId: '1:587521772116:android:c993442a823b0cad877bc1',
    messagingSenderId: '587521772116',
    projectId: 'medicalapp-b6c2e',
    databaseURL: 'https://medicalapp-b6c2e-default-rtdb.firebaseio.com',
    storageBucket: 'medicalapp-b6c2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkQZY5Zx8qjKRVLddGctq7m1X9vvPEYEs',
    appId: '1:587521772116:ios:3603fefbe281c0aa877bc1',
    messagingSenderId: '587521772116',
    projectId: 'medicalapp-b6c2e',
    databaseURL: 'https://medicalapp-b6c2e-default-rtdb.firebaseio.com',
    storageBucket: 'medicalapp-b6c2e.appspot.com',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkQZY5Zx8qjKRVLddGctq7m1X9vvPEYEs',
    appId: '1:587521772116:ios:0631695186040397877bc1',
    messagingSenderId: '587521772116',
    projectId: 'medicalapp-b6c2e',
    databaseURL: 'https://medicalapp-b6c2e-default-rtdb.firebaseio.com',
    storageBucket: 'medicalapp-b6c2e.appspot.com',
    iosBundleId: 'com.example.medicalApp.RunnerTests',
  );
}
